MODEL:
  DEVICE: "cuda"
  DEVICE_ID: ('1')
  MODE: 'test'
  DETECTION: 'gt' # {'gt'}
  RESUME: false
  LAST_CKPT_FILE: './'

DATASET:
  DIR: './datasets/'
  NAME: 'CAMPUS'
  SEQUENCE: ['Garden2'] # {'Garden1' | 'Garden2' | 'Parkinglot'}
  CAMS: 4
  TOTAL_FRAMES: 6000 # 'Garden1':2849, 'Garden2': 6000, 'Parkinglot': 6475

FE: # Feature Extractor
  CHOICE: 'CNN'
  INPUT_SIZE: (256, 128)

SOLVER:
  TYPE: 'SG' # {'SG': Spatial Graph, 'TG': Temporal Graph}
  EPOCHS: 100
  EVAL_EPOCH: 2
  BATCH_SIZE: 100
  LR: 0.01 # Learning Rate
  MAX_PASSING_STEPS: 4
  W: 3 # Temporal Window Size
  W_TEST: 5
  FOCAL_ALPHA: 0.98
  FOCAL_GAMMA: 5

OUTPUT:
  VISUALIZE: False
  LOG: True
  CKPT_DIR: './logs/ckpts'
  INFERENCE_DIR: './logs/inference'

TEST:
  CKPT_FILE_SG: './'
  CKPT_FILE_TG: './'
  FRAME_START: 4800 # 'Garden1': 2280; 'Garden2': 4800; 'Parkinglot': 5828
  EDGE_THRESH: 0.9